-- FalconDB PoC #3 — Failover Under Load: Commit Marker Table
-- Each marker_id is generated by the client and logged ONLY after COMMIT OK.
-- This table is the source of truth for verification.

CREATE TABLE IF NOT EXISTS tx_markers (
    marker_id     BIGINT PRIMARY KEY,
    created_at    TIMESTAMP DEFAULT NOW(),
    source_node   TEXT
);
