-- FalconDB DCG PoC — Order Schema
-- This table stores simulated financial orders.
-- Each order_id is generated by the client and logged ONLY after COMMIT succeeds.

CREATE TABLE IF NOT EXISTS orders (
    order_id    BIGINT PRIMARY KEY,
    created_at  TIMESTAMP DEFAULT NOW(),
    payload     TEXT
);
