use crate::types::ScalarFunc;

/// Resolve a SQL function name to its ScalarFunc variant.
/// Returns None for functions that need special handling (aggregates, NOW, DATE_TRUNC, etc).
pub fn resolve_scalar_func(name: &str) -> Option<ScalarFunc> {
    Some(match name {
        // ── String functions ──
        "UPPER" => ScalarFunc::Upper,
        "LOWER" => ScalarFunc::Lower,
        "LENGTH" | "CHAR_LENGTH" | "CHARACTER_LENGTH" => ScalarFunc::Length,
        "SUBSTR" => ScalarFunc::Substring,
        "CONCAT" => ScalarFunc::Concat,
        "CONCAT_WS" => ScalarFunc::ConcatWs,
        "TRIM" => ScalarFunc::Trim,
        "BTRIM" => ScalarFunc::Btrim,
        "LTRIM" => ScalarFunc::Ltrim,
        "RTRIM" => ScalarFunc::Rtrim,
        "REPLACE" => ScalarFunc::Replace,
        "POSITION" | "STRPOS" => ScalarFunc::Position,
        "LPAD" => ScalarFunc::Lpad,
        "RPAD" => ScalarFunc::Rpad,
        "LEFT" => ScalarFunc::Left,
        "RIGHT" => ScalarFunc::Right,
        "REPEAT" => ScalarFunc::Repeat,
        "REVERSE" => ScalarFunc::Reverse,
        "INITCAP" => ScalarFunc::Initcap,
        "TRANSLATE" => ScalarFunc::Translate,
        "SPLIT_PART" => ScalarFunc::Split,
        "OVERLAY" => ScalarFunc::Overlay,
        "STARTS_WITH" => ScalarFunc::StartsWith,
        "ENDS_WITH" => ScalarFunc::EndsWith,
        "CHR" => ScalarFunc::Chr,
        "ASCII" => ScalarFunc::Ascii,
        "QUOTE_LITERAL" => ScalarFunc::QuoteLiteral,
        "QUOTE_IDENT" => ScalarFunc::QuoteIdent,
        "QUOTE_NULLABLE" => ScalarFunc::QuoteNullable,
        "BIT_LENGTH" => ScalarFunc::BitLength,
        "OCTET_LENGTH" => ScalarFunc::OctetLength,
        "FORMAT" => ScalarFunc::Format,
        "SUBSTR_COUNT" | "STRCOUNT" => ScalarFunc::SubstrCount,
        "NORMALIZE" => ScalarFunc::Normalize,
        "PARSE_IDENT" => ScalarFunc::ParseIdent,
        // ── Math functions ──
        "ABS" => ScalarFunc::Abs,
        "ROUND" => ScalarFunc::Round,
        "CEIL" | "CEILING" => ScalarFunc::Ceil,
        "FLOOR" => ScalarFunc::Floor,
        "POWER" | "POW" => ScalarFunc::Power,
        "SQRT" => ScalarFunc::Sqrt,
        "SIGN" => ScalarFunc::Sign,
        "TRUNC" | "TRUNCATE" => ScalarFunc::Trunc,
        "LN" => ScalarFunc::Ln,
        "LOG" => ScalarFunc::Log,
        "EXP" => ScalarFunc::Exp,
        "PI" => ScalarFunc::Pi,
        "MOD" => ScalarFunc::Mod,
        "DEGREES" => ScalarFunc::Degrees,
        "RADIANS" => ScalarFunc::Radians,
        "GREATEST" => ScalarFunc::Greatest,
        "LEAST" => ScalarFunc::Least,
        "CBRT" => ScalarFunc::Cbrt,
        "FACTORIAL" => ScalarFunc::Factorial,
        "GCD" => ScalarFunc::Gcd,
        "LCM" => ScalarFunc::Lcm,
        "SIN" => ScalarFunc::Sin,
        "COS" => ScalarFunc::Cos,
        "TAN" => ScalarFunc::Tan,
        "ASIN" => ScalarFunc::Asin,
        "ACOS" => ScalarFunc::Acos,
        "ATAN" => ScalarFunc::Atan,
        "ATAN2" => ScalarFunc::Atan2,
        "LOG10" => ScalarFunc::Log10,
        "LOG2" => ScalarFunc::Log2,
        "COT" => ScalarFunc::Cot,
        "SINH" => ScalarFunc::Sinh,
        "COSH" => ScalarFunc::Cosh,
        "TANH" => ScalarFunc::Tanh,
        "ASINH" => ScalarFunc::Asinh,
        "ACOSH" => ScalarFunc::Acosh,
        "ATANH" => ScalarFunc::Atanh,
        "WIDTH_BUCKET" => ScalarFunc::WidthBucket,
        "DIV" => ScalarFunc::Div,
        "SCALE" => ScalarFunc::Scale,
        "ISFINITE" => ScalarFunc::Isfinite,
        "ISINF" => ScalarFunc::Isinf,
        "ISNAN" => ScalarFunc::Isnan,
        "TRIM_SCALE" => ScalarFunc::TrimScale,
        "MIN_SCALE" | "MINSCALE" => ScalarFunc::MinScale,
        "TRUNC_PRECISION" => ScalarFunc::TruncPrecision,
        "ROUND_PRECISION" => ScalarFunc::RoundPrecision,
        "CLAMP" => ScalarFunc::Clamp,
        // ── Date/Time functions ──
        "AGE" => ScalarFunc::Age,
        "MAKE_DATE" => ScalarFunc::MakeDate,
        "MAKE_TIMESTAMP" => ScalarFunc::MakeTimestamp,
        "TO_TIMESTAMP" => ScalarFunc::ToTimestamp,
        "CLOCK_TIMESTAMP" => ScalarFunc::ClockTimestamp,
        "STATEMENT_TIMESTAMP" => ScalarFunc::StatementTimestamp,
        "TIMEOFDAY" => ScalarFunc::Timeofday,
        "TO_DATE" => ScalarFunc::ToDate,
        "DATE_ADD" => ScalarFunc::DateAdd,
        "DATE_SUBTRACT" | "DATE_SUB" => ScalarFunc::DateSubtract,
        "DATE_DIFF" | "DATEDIFF" => ScalarFunc::DateDiff,
        "EPOCH_FROM_TIMESTAMP" | "EXTRACT_EPOCH" => ScalarFunc::EpochFromTimestamp,
        "MAKE_INTERVAL" => ScalarFunc::MakeInterval,
        "TO_CHAR" => ScalarFunc::ToChar,
        // ── Array functions ──
        "ARRAY_LENGTH" => ScalarFunc::ArrayLength,
        "CARDINALITY" => ScalarFunc::Cardinality,
        "ARRAY_POSITION" => ScalarFunc::ArrayPosition,
        "ARRAY_POSITIONS" => ScalarFunc::ArrayPositions,
        "ARRAY_APPEND" => ScalarFunc::ArrayAppend,
        "ARRAY_PREPEND" => ScalarFunc::ArrayPrepend,
        "ARRAY_REMOVE" => ScalarFunc::ArrayRemove,
        "ARRAY_REPLACE" => ScalarFunc::ArrayReplace,
        "ARRAY_CAT" => ScalarFunc::ArrayCat,
        "ARRAY_TO_STRING" => ScalarFunc::ArrayToString,
        "STRING_TO_ARRAY" => ScalarFunc::StringToArray,
        "ARRAY_UPPER" => ScalarFunc::ArrayUpper,
        "ARRAY_LOWER" => ScalarFunc::ArrayLower,
        "ARRAY_DIMS" => ScalarFunc::ArrayDims,
        "ARRAY_FILL" => ScalarFunc::ArrayFill,
        "ARRAY_REVERSE" => ScalarFunc::ArrayReverse,
        "ARRAY_DISTINCT" => ScalarFunc::ArrayDistinct,
        "ARRAY_SORT" => ScalarFunc::ArraySort,
        "ARRAY_CONTAINS" => ScalarFunc::ArrayContains,
        "ARRAY_OVERLAP" | "ARRAYS_OVERLAP" => ScalarFunc::ArrayOverlap,
        "ARRAY_SLICE" => ScalarFunc::ArraySlice,
        "ARRAY_NDIMS" => ScalarFunc::ArrayNdims,
        "UNNEST" => ScalarFunc::Unnest,
        "STRING_TO_TABLE" => ScalarFunc::StringToTable,
        "ARRAY_TO_JSON" => ScalarFunc::ArrayToJson,
        "ARRAY_GENERATE" => ScalarFunc::ArrayGenerate,
        "ARRAY_SAMPLE" => ScalarFunc::ArraySample,
        "ARRAY_SHUFFLE" => ScalarFunc::ArrayShuffle,
        "ARRAY_INTERSECT" => ScalarFunc::ArrayIntersect,
        "ARRAY_EXCEPT" => ScalarFunc::ArrayExcept,
        "ARRAY_COMPACT" | "ARRAY_REMOVE_NULLS" => ScalarFunc::ArrayCompact,
        "ARRAY_FLATTEN" => ScalarFunc::ArrayFlatten,
        "ARRAY_REPEAT" => ScalarFunc::ArrayRepeat,
        "ARRAY_ROTATE" => ScalarFunc::ArrayRotate,
        "ARRAY_TO_SET" => ScalarFunc::ArrayToSet,
        "ARRAY_ZIP" => ScalarFunc::ArrayZip,
        "ARRAY_MIN" => ScalarFunc::ArrayMin,
        "ARRAY_MAX" => ScalarFunc::ArrayMax,
        "ARRAY_SUM" => ScalarFunc::ArraySum,
        "ARRAY_AVG" => ScalarFunc::ArrayAvg,
        "ARRAY_EVERY" => ScalarFunc::ArrayEvery,
        "ARRAY_SOME" => ScalarFunc::ArraySome,
        "OVERLAY_ARRAY" => ScalarFunc::OverlayArray,
        // ── Regex functions ──
        "REGEXP_REPLACE" => ScalarFunc::RegexpReplace,
        "REGEXP_MATCH" | "REGEXP_MATCHES" => ScalarFunc::RegexpMatch,
        "REGEXP_COUNT" => ScalarFunc::RegexpCount,
        "REGEXP_SUBSTR" => ScalarFunc::RegexpSubstr,
        "REGEXP_SPLIT_TO_ARRAY" => ScalarFunc::RegexpSplitToArray,
        "REGEXP_INSTR" => ScalarFunc::RegexpInstr,
        "REGEXP_LIKE" => ScalarFunc::RegexpLike,
        "REGEXP_ESCAPE" => ScalarFunc::RegexpEscape,
        // ── Crypto/encoding ──
        "MD5" => ScalarFunc::Md5,
        "SHA256" | "DIGEST" => ScalarFunc::Sha256,
        "ENCODE" => ScalarFunc::Encode,
        "DECODE" => ScalarFunc::Decode,
        "TO_HEX" => ScalarFunc::ToHex,
        "HASHTEXT" => ScalarFunc::Hashtext,
        "CRC32" => ScalarFunc::Crc32,
        // ── Bit operations ──
        "BIT_XOR" => ScalarFunc::BitXor,
        "BIT_AND_FUNC" => ScalarFunc::BitAnd,
        "BIT_OR_FUNC" => ScalarFunc::BitOr,
        "BIT_COUNT" => ScalarFunc::BitCount,
        "BIT_NOT" => ScalarFunc::BitNot,
        // ── Utility ──
        "PG_TYPEOF" | "TYPEOF" => ScalarFunc::PgTypeof,
        "TO_NUMBER" => ScalarFunc::ToNumber,
        "RANDOM" => ScalarFunc::Random,
        "GEN_RANDOM_UUID" => ScalarFunc::GenRandomUuid,
        "NUM_NONNULLS" => ScalarFunc::NumNonnulls,
        "NUM_NULLS" => ScalarFunc::NumNulls,
        // ── Fuzzy string matching (fuzzystrmatch) ──
        "LEVENSHTEIN" => ScalarFunc::Levenshtein,
        "SOUNDEX" => ScalarFunc::Soundex,
        "DIFFERENCE" => ScalarFunc::Difference,
        "SIMILARITY" => ScalarFunc::Similarity,
        "HAMMING_DISTANCE" => ScalarFunc::HammingDistance,
        // ── JSONB ──
        "JSONB_BUILD_OBJECT" => ScalarFunc::JsonbBuildObject,
        "JSONB_BUILD_ARRAY" => ScalarFunc::JsonbBuildArray,
        "JSONB_TYPEOF" | "JSON_TYPEOF" => ScalarFunc::JsonbTypeof,
        "JSONB_ARRAY_LENGTH" | "JSON_ARRAY_LENGTH" => ScalarFunc::JsonbArrayLength,
        "JSONB_EXTRACT_PATH" | "JSON_EXTRACT_PATH" => ScalarFunc::JsonbExtractPath,
        "JSONB_EXTRACT_PATH_TEXT" | "JSON_EXTRACT_PATH_TEXT" => ScalarFunc::JsonbExtractPathText,
        "JSONB_OBJECT_KEYS" | "JSON_OBJECT_KEYS" => ScalarFunc::JsonbObjectKeys,
        "JSONB_PRETTY" => ScalarFunc::JsonbPretty,
        "JSONB_STRIP_NULLS" | "JSON_STRIP_NULLS" => ScalarFunc::JsonbStripNulls,
        "JSONB_SET" => ScalarFunc::JsonbSetPath,
        "TO_JSONB" | "TO_JSON" => ScalarFunc::ToJsonb,
        "JSONB_AGG" | "JSON_AGG" => ScalarFunc::JsonbAgg,
        "JSONB_CONCAT" => ScalarFunc::JsonbConcat,
        "JSONB_DELETE_KEY" => ScalarFunc::JsonbDeleteKey,
        "JSONB_DELETE_PATH" => ScalarFunc::JsonbDeletePath,
        "JSONB_POPULATE_RECORD" => ScalarFunc::JsonbPopulateRecord,
        "JSONB_ARRAY_ELEMENTS" | "JSON_ARRAY_ELEMENTS" => ScalarFunc::JsonbArrayElements,
        "JSONB_ARRAY_ELEMENTS_TEXT" | "JSON_ARRAY_ELEMENTS_TEXT" => {
            ScalarFunc::JsonbArrayElementsText
        }
        "JSONB_EACH" | "JSON_EACH" => ScalarFunc::JsonbEach,
        "JSONB_EACH_TEXT" | "JSON_EACH_TEXT" => ScalarFunc::JsonbEachText,
        "ROW_TO_JSON" => ScalarFunc::RowToJson,
        _ => {
            // Pattern-based resolution for generated extended functions
            if name.starts_with("ARRAY_MATRIX_") {
                return Some(ScalarFunc::ArrayMatrixFunc(name.to_owned()));
            }
            if let Some(stem) = name.strip_suffix("_ENCODE") {
                if stem.starts_with("STRING_") {
                    return Some(ScalarFunc::StringEncodingFunc {
                        name: stem.to_owned(),
                        encode: true,
                    });
                }
            }
            if let Some(stem) = name.strip_suffix("_DECODE") {
                if stem.starts_with("STRING_") {
                    return Some(ScalarFunc::StringEncodingFunc {
                        name: stem.to_owned(),
                        encode: false,
                    });
                }
            }
            return None;
        }
    })
}
